/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as V1RouteImport } from './routes/V1Route'
import { Route as RootRouteImport } from './routes/RootRoute'
import { Route as IndexRouteImport } from './routes/IndexRoute'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const V1RouteRoute = V1RouteImport.update({
  path: '/V1Route',
  getParentRoute: () => rootRoute,
} as any)

const RootRouteRoute = RootRouteImport.update({
  path: '/RootRoute',
  getParentRoute: () => rootRoute,
} as any)

const IndexRouteRoute = IndexRouteImport.update({
  path: '/IndexRoute',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/IndexRoute': {
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/RootRoute': {
      preLoaderRoute: typeof RootRouteImport
      parentRoute: typeof rootRoute
    }
    '/V1Route': {
      preLoaderRoute: typeof V1RouteImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  IndexRouteRoute,
  RootRouteRoute,
  V1RouteRoute,
])

/* prettier-ignore-end */
